#pragma once
// Every game global the decompiled code references, one declaration per address,
// sorted by address.
#include "types.h"

extern char g_hiscoresCleared;
extern unsigned char g_introInit;
extern unsigned char g_directX;
extern int g_endPic;
extern int g_aiTimer;
extern int g_viewTransitionFlag;
extern int g_shopEntryFlag;
extern float g_joyCenter;
extern float g_joyDead;
extern float g_joystickSpeedMul;
extern int g_prevMouseX;
extern int g_prevMouseY;
extern int g_mouseX;
extern int g_mouseY;
extern int g_clicked;
extern int g_pressed;
extern int g_shopHoverItem;
extern int g_bgIndex;
extern float g_angle1;
extern float g_angle2;
extern int g_endSequenceActive;
extern unsigned int g_animInterval;
extern int g_pulseHoldCount;
extern int g_pulseCycleTimer;
extern float g_offX;
extern float g_shopSlideVelX;
extern float g_offY;
extern float g_shopSlideVelY;
extern float g_shopBounceY;
extern int g_grabZoneHit;
extern unsigned int g_blinkRate;
extern unsigned int g_cursorBlinkRate;
extern int g_textAutoY;
extern float g_hiscoreScrollX;
extern float g_hiscoreScrollY;
extern int g_logoSplashTimer;
extern unsigned int g_idleTimeoutMs;
extern int g_screenDelayMs;
extern float g_chargeMax;
extern float g_chargeRate;
extern float g_dischargeRate;
// Anti-cheat value obfuscation (always 7), against memory editing: the score, price and
// bonus tables hold every value multiplied by this, and the game divides it back out
// wherever it reads one, so a memory editor searching for a known price or reward finds
// nothing to change. (The player's own money and score are stored plain.)
extern __int64 g_valueObfuscationMult;
#define OBFUSCATE_VALUE(v)   (g_valueObfuscationMult * (v))
#define DEOBFUSCATE_VALUE(v) ((v) / g_valueObfuscationMult)
extern int g_scoreUnit;
extern float g_starPulseAlphaStep;
extern int g_objSrcX[];
extern int g_objSrcY[];
extern int g_objW[];
extern int g_objH[];
extern float g_debrisVySpeedFactor[];
extern float g_starXMin;
extern float g_debrisVxFactor[];
extern float g_starXMax;
extern int g_debrisLinkType1[];
extern float g_starYMin;
extern int g_debrisLinkType2[];
extern float g_starYMax;
extern int g_debrisYOffset[];
extern float g_starZFar;
extern int g_debrisXOffset[];
extern int g_debrisNextType[];
extern float g_bulletSpeedMax;
extern int g_levelEnemyColorR;
extern int g_debrisLaserFlag[];
extern int g_levelEnemyColorG;
extern int g_debrisParticleSize[];
extern int g_levelEnemyColorB;
extern int g_debrisParticleColorR[];
extern float g_shopTransition;
extern int g_debrisParticleColorG[];
extern int g_debrisParticleColorB[];
extern int g_demoSteer;
extern int g_debrisParticleAlpha[];
extern float g_starSpeedX;
extern float g_starSpeedY;
extern int g_objR[];
extern float g_starSpeedZ;
extern int g_objG[];
extern unsigned int g_tallyDelay;
extern int g_objB[];
extern int g_guardCount;
extern int g_objFlameOn[];
extern int g_bonusIconFrame1;
extern int g_bonusIconFrame2;
extern int g_bonusIconFrame3;
extern int g_bonusIconFrame4;
extern int g_bonusIconFrame5;
extern int g_objFlameGfx[];
extern int g_objFlameAngle[];
extern float g_bonusIconAnimTimer;
extern int g_objFlameHalfW[];
extern int g_objFlameHalfH[];
extern int g_objFlameOffY[];
extern int g_malfunctionBeepCount;
extern int g_shotType[];
extern float g_shotSpeed[];
extern int g_explSrcX[];
extern int g_explW[];
extern int g_explH[];
extern int g_expl2SrcX[];
extern int g_expl2SrcY[];
extern float g_tiltStep;
extern char g_perfect[];
extern bool g_meterDirUp;
extern unsigned char g_tryDirectX;
extern char g_perfectBlank[];
extern int g_secretPicCur;
extern int g_secretPicPrev;
extern int g_secretPic;
extern int g_shopPic;
extern int g_secretPicPick;
extern int g_numLevels;
extern float g_newsX;
extern float g_newsSpeed;
extern int g_font;
extern int g_speedPctCache;
extern int g_animTickA;
extern FPair g_dirSlopeRange[];
extern int g_dirRemap[];
extern int g_rot16SrcX[];
extern int g_rot16AltSrcX[];
extern int g_rot16SrcY[];
extern int g_rot16AltSrcY[];
extern Box g_boxesA[];
extern Box g_boxesB[];
extern float g_dirVecX[];
extern float g_dirVecY[];
extern float g_dirVecX2[];
extern float g_dirVecY2[];
extern int g_animTickB;
extern int g_animTickC;
extern int g_shopUpEdge;
extern int g_shopDownEdge;
extern int g_jukeboxKeyLatch;
extern int g_screenshotKeyEdge;
extern int g_shopKeyLatchD;
extern int g_f9KeyLatch;
extern int g_checkUpdateKeyLatch;
extern int g_newsFeedKeyLatch;
extern int g_shopFireEdge;
extern int g_shopPrevItem;
extern int g_shopActiveTimer;
extern int g_musicMode;
extern int g_playlistIdx;
extern int g_fadeOnce;
extern int g_bonusWeight[37];
extern float g_coinVySpeedTable[];
extern int g_itemBonusSrcY[];
extern int g_coinSrcYTable[];
extern int g_itemHeightTable[];
extern int g_coinTypeTable[];
extern int g_itemWidthTable[];
extern int g_noSpritesDrawn;
extern int g_itemFrameCountTable[];
extern int g_malfunctionTimer;
extern int g_itemTypePool[];
extern float g_scoopYScale;
extern float g_meterY;
extern int g_dragWin;
extern int g_pressWin;
extern int g_pressItem;
extern int g_pressLink;
extern int g_clickWin;
extern int g_clickItem;
extern int g_clickLink;
extern int g_maxSparks;
extern int g_livesGainedCount;
extern int g_bonusRoundTypePool[];
extern int g_hsEntryIndex;
extern int g_weights[];
extern int g_memorySecretBirdSnapshot;
extern int g_hsRank[4];
extern int g_hsPlayer[4];
extern int g_hsRank2[4];
extern int g_hsPlayer2[4];
extern float g_bonusSpawnTarget;
extern int g_meteorSrcX[];
extern int g_bonusSrcY[];
extern int g_bonusGfxW[46];
extern int g_bonusGfxH[46];
extern float g_maxFallingGems;
extern float g_maxFallingGemsInc;
extern int g_maxBuffered;
extern int g_levelLoadingFlag;
extern int g_bossIdx;
extern int g_memHoverRow;
extern int g_memHoverCol;
extern int g_memCountdownStage;
extern int g_raceCountdownStage;
extern int g_memPendingCardType;
extern int g_selProfile;
extern int g_profileIndex;
extern int g_profileWin;
extern int g_quitGameWin;
extern int g_quitWinWin;
extern int g_shopItems;
extern int g_version;
extern int g_rankSprY[];
extern int g_weaponRow[];
extern float g_gameVersion;
extern char g_rankNames[][0x22];
extern unsigned char g_freshStart;
extern int g_pressedKey;
extern SOCKET g_socket;
extern unsigned char g_playerBroke;
extern bool g_newsFail;
extern float g_gameSpeedMul;
extern int g_shipStats0[];
extern int g_foundSlot;
extern int g_foundChan;
extern char g_shopPics[][30];
extern char g_secretPics[][30];
extern int g_armourAddedCount;
extern int g_shipStats6[];
extern int g_deathsCount;
extern int g_engineFreqMax;
extern int g_engineFreqMin;
extern float g_targetItemX;
extern float g_targetItemY;
extern float g_targetObjX;
extern float g_targetObjY;
extern float g_target847X;
extern float g_targetB49X;
extern float g_targetB49Y;
extern int g_ringSize[];
extern int g_ringR[];
extern int g_ringG[];
extern int g_ringB[];
extern int g_streakColorR;
extern int g_streakColorG;
extern float g_streakHalfSize;
extern float g_streakY;
extern float g_streakAlphaStep;
extern float g_streakSpinSpeed0;
extern float g_streakSpinSpeed1;
extern float g_streakSpinSpeed2;
extern int g_bannerY;
extern int g_bannerCenterX;
extern int g_bannerCenterY;
extern int g_bannerHalfW;
extern int g_bannerHalfH;
extern int g_logoAnchorX;
extern int g_logoAnchorY;
extern int g_bannerShrink;
extern float g_leftWingY;
extern float g_leftWingSize;
extern float g_leftWingAngleBase;
extern float g_leftWingAngleDecay;
extern float g_rightWingY;
extern float g_rightWingSize;
extern float g_rightWingAngleBase;
extern float g_rightWingAngleDecay;
extern float g_wordmarkShrinkW;
extern float g_wordmarkShrinkH;
extern float g_centerScale;
extern float g_starRayAngle1;
extern float g_starRayAngle2;
extern float g_starRayAngle3;
extern float g_starRayAngle4;
extern float g_starRayAngle5;
extern int g_starYOffset;
extern int g_shipStats7[];
extern int g_shipStats9[];
extern int g_shipStats2[];
extern float g_wobbleSpeed;
extern float g_endDR;
extern float g_endDG;
extern float g_endDB;
extern int g_shipStats1[];
extern int g_speedBarP0;
extern int g_smallFontWidths[];
extern int g_ammoBarP0;
extern int g_timeBarP0;
extern int g_fireRateBarP0;
extern int g_speedBarP1;
extern int g_ammoBarP1;
extern int g_timeBarP1;
extern int g_fireRateBarP1;
extern int g_speedBarP2;
extern int g_ammoBarP2;
extern int g_timeBarP2;
extern int g_fireRateBarP2;
extern int g_speedBarP3;
extern int g_ammoBarP3;
extern int g_timeBarP3;
extern int g_fireRateBarP3;
extern int g_shipStats5[];
extern int g_flareCnt0;
extern int g_flareCnt1;
extern int g_flareCnt2;
extern int g_flareCnt3;
extern int g_flareOfs[11][11];
extern int g_flareSize;
extern int g_digitX[];
extern int g_digitW[];
extern float g_bonusFxX;
extern float g_bonusFxVel;
extern int g_shipStats3[];
extern float g_bossAnimStep;
extern int g_shipStats4[];
extern int g_shipStats8[];
extern unsigned int g_screenW;
extern unsigned int g_screenH;
extern int g_windowBpp;
extern float g_worldZoomInit;
extern float g_worldZoom;
extern unsigned int g_exitSoundStartTime;
extern BurstSpark g_slots[1000];
extern Pattern g_pattern;
extern LinkArea g_links[];
extern HyperspaceStar g_stars[3000];
extern unsigned int g_pauseLastTick;
extern int g_hazard0GfxH;
extern void *g_scratchPoolD;
extern int g_pend5Freq;
extern int g_moneyShipGfxW;
extern float g_msgPanX;
extern int g_msgColor;
extern int g_hazard4GfxW;
extern Beam g_beams[12];
extern char g_news4[];
extern Flash g_sparkleFlashes[10];
extern int g_bonusKillCombo[];
extern int g_ship2GfxParamA;
extern FrameSet g_frames[6];
extern int g_rocketGfxW;
extern AlienGfxSlot g_alienGfxSlots[200];
extern KGraphic *g_gfxRankPlanets;
extern int g_hazard5GfxW;
extern char g_sRank[];
extern short g_perfectColorTable[512];
extern int g_sampleVol[10];
extern float g_grabZoneWidthTable[100];
extern Card g_cards[][8];
extern int g_portalGfxW;
extern Rect16 g_blitSrc;
extern int g_pend1Freq;
extern FallingSprite g_fallingGems[];
extern int g_accSize;
extern VoidFn g_bulletsVsPlayerFn;
extern float g_pend1Pan;
extern char g_sB[];
extern VoidFn g_drawHudFn;
extern float g_enemyVelXScratch;
extern char g_speedPctText[];
extern Explosion g_explosions[50];
extern int g_hazard2GfxH;
extern Rect16 g_rectsA[6];
extern int g_animFrameCount;
extern float g_fxColorSpeedR;
extern SaveData g_save;
extern Enemy g_enemies[2][150];
extern LevelRec g_levelRecs[4000];
extern int g_curLevelNum;
extern int g_levelDataLoaded;
extern int g_loadedLevel;
extern int g_warpLevelR;
extern int g_warpLevelL;
extern unsigned char g_marksBonusGiven;
extern unsigned char g_enemyAimAtPlayer;
extern unsigned char g_fastEnemyBullets;
extern int g_diffEnemyFireChance;
extern int g_diffShotFuseBase;
extern int g_diffShotFuseRange;
extern int g_hurryUpInterval;
extern float g_diffShotSpeedMin;
extern float g_diffShotSpeedMax;
extern float g_diffTurretTrackChance;
extern float g_diffBonusDropRoll;
extern int g_curPlayer;
extern int g_shopCurPlayer;
extern int g_promoPlayer;
extern int g_bonusStagePlayer;
extern int g_vsTurnPlayer;
extern int g_saveVersion;
extern int g_diffScoreBonus;
extern float g_defaultObjAlpha;
extern float g_enemyBulletSpeed;
extern float g_playerStartSpeed;
extern float g_diffEnemyTimerMul;
extern int g_diffEnemyHpBonus;
extern int g_moneySuckerBaseHp;
extern float g_diffHurryUpSpeedMax;
extern int g_eliteHpBonus;
extern int g_hurryUpHpBonus;
extern float g_speedBase;
extern float g_speedStep;
extern float g_maxSpeedMul;
extern float g_speedMax;
extern int g_bonusDuration;
extern float g_bonusSpawnRampRate;
extern int g_bonusThresholdBase;
extern int g_bonusRareChance;
extern int g_timeMax;
extern int g_speedMin;
extern int g_lastEliteSpawnLevel;
extern int g_fireDelayMin;
extern int g_enemyFireRateMin;
extern int g_fireDelayBiasA;
extern int g_fireDelayBiasB;
extern __int64 g_resumeTimeOffset;
extern int g_comboLevel;
extern int g_comboStep;
extern int g_sessionScore;
extern int g_hits;
extern int g_gameMode;
extern int g_pendingGameMode;
extern int g_hofMode;
extern int g_savedDifficultySave;
extern int g_perfectCount;
extern int g_killCount;
extern char *g_playlistLines[10000];
extern float g_sinTable[3600];
extern KGraphic *g_screen;
extern Ring g_flash[4];
extern FadeColors g_colR[];
extern int g_exitSoundElapsed;
extern int g_fadeFreq2;
extern int g_frameAX1;
extern float g_starX[3000];
extern char g_hiscorePackedOld[];
extern unsigned int g_rngT;
extern float g_pend2Pan;
extern char g_levelName[];
extern LARGE_INTEGER g_timeStampA;
extern int g_pend5Vol;
extern char g_hiscoreBuf[];
extern Account g_acc;
extern const char *g_songName;
extern LARGE_INTEGER g_pauseStartStamp;
extern Level g_curLevelData;
extern VoidFn g_frameFunc;
extern unsigned int g_time;
extern char g_sC[];
extern int g_attractScreen;
extern SoundQueueEntry g_soundQueue[10];
extern int g_diamondGfxH;
extern char g_songNames[][260];
extern char g_strE[260];
extern int g_screenTimerStart;
extern __int64 g_scoreMul[];
extern float g_starY[3000];
extern int g_ship1GfxParamB;
extern Particle g_explosionParticles[500];
extern int g_lastFrameTick;
extern int g_fadeFreq1;
extern Pattern g_patterns[];
extern float g_sinDeg[360];
extern VoidFn g_stateFn;
extern char g_scoreBuf[];
extern int g_sfxVolTable[256];
extern char g_sLevel[];
extern float g_pend4Pan;
extern int g_pend1Vol;
extern int g_pend0Freq;
extern LARGE_INTEGER g_playTimeFt;
extern float g_panTable[];
extern float g_pan;
extern int g_meteorsGfxH;
extern float g_pend3Pan;
extern int g_pend4Vol;
extern char g_news1[];
extern short g_animColScratch;
extern void *g_scratchPoolA;
extern int g_pend2Freq;
extern int g_fadeFreq4;
extern int g_guardWidth;
extern Settings g_cfg;
extern LevelObj g_levelObj[100];
extern char g_msgBuf[];
extern int g_flashOverlayActive;
extern int g_diamondGfxW;
extern int g_state;
extern char g_strD[260];
extern LARGE_INTEGER g_pausedDuration;
extern int g_hiscoreSize;
extern char g_concatBuf[];
extern int g_levelStarted;
extern int g_cursorBlinkOn;
extern unsigned int g_raceHoldTime;
extern int g_moneySuckerWidth;
extern void *g_scratchPoolE;
extern char g_alertMsg[];
extern float g_fxColorG;
extern void(*g_playerUpdateFn)();
extern char g_songPath[1024];
extern char g_strH[260];
extern int g_hazard4GfxH;
extern AccountV2 g_accV2;
extern int g_rocketGfxH;
extern char g_buf[];
extern int g_tallyStep;
extern int g_bonusGfxArea[46];
extern LARGE_INTEGER g_perfTimerStart;
extern unsigned int g_lastTick;
extern char g_newsBuf[];
extern unsigned int g_rngZ;
extern int g_coinGfxH;
extern int g_diamondBigGfxH;
extern int g_ship1GfxParamA;
extern int g_frameBX1;
extern int g_gfxWeaponsBigW;
extern void *g_scratchPoolC;
extern unsigned int g_fps;
extern VoidFn g_drawLevelObjectsFn;
extern VoidFn g_itemsVsPlayerFn;
extern int g_frameBX2;
extern int g_ship2GfxParamB;
extern int g_groupKillCount[];
extern int g_lockOnLevelInitParam;
extern int g_musVolTable[256];
extern int g_frameAX2;   // was declared as a Bonus view at 8 bytes before g_items
extern int g_warpMsgBlinkOn;
extern Bonus g_items[150];
extern char g_sName[];
extern unsigned int g_rngY;
extern int g_coinGfxW;
extern float g_sfxVolume;
extern char g_moneyBuf1[];
extern int g_frameDeltaMs;
extern int g_keyLatch[256];
extern BASS_DWORD g_samples[4][150];
extern KGraphic *g_gfxBird;
extern int g_pend0Vol;
extern char g_bonusNumBuf[];
extern float g_fxGreenVel;
extern int g_rampB[];
extern int g_sfxFreq;
extern int g_sampleRate[10];
extern char g_optionMsg[];
extern int g_frameBY1;
extern unsigned int g_lastFpsTime;
extern char g_strM[260];
extern __int64 g_hiscore;
extern FreeParticle g_particles[];
extern int g_hazard3GfxW;
extern VoidFn g_fnPtr;
extern int g_portalGfxW2;
extern unsigned int g_prevFps;
extern char g_getReadyText[];
extern char g_sD[];
extern int g_mothershipMaskH;
extern FallingHazard g_bonusMeteors[30];
extern int g_frameBY2;
extern float g_fadePan2;
extern char g_moneyBuf2[];
extern float g_fxRed;
extern int g_guardHeight;
extern char g_strP[260];
extern int g_hazard3GfxH;
extern ShipDef *g_shipDefs[];
extern int *g_shipStatsPtr1;
extern int *g_shipStatsPtr2;
extern int *g_shipStatsPtr3;
extern int *g_shipStatsPtr4;
extern int *g_shipStatsPtr5;
extern int *g_shipStatsPtr6;
extern int *g_shipStatsPtr7;
extern int *g_shipStatsPtr8;
extern int *g_shipStatsPtr9;
extern char g_moneyBuf3[];
extern float g_fxBlueVel;
extern char g_sA[];
extern VoidFn g_drawBordersFn;
extern char g_newName[];
extern int g_bonusItemGfxH;
extern int g_moneyShipGfxH;
extern int g_savedState;
extern int g_meteorBonusesGfxW;
extern void *g_scratchPoolB;
extern LARGE_INTEGER g_pauseEndStamp;
extern char g_staleErrBuf[];
extern int g_gfxWeaponsBigH;
extern char g_sE[];
extern int g_pend3Freq;
extern int g_tallyState;
extern HiscoreData g_hiscoresOld;
extern KGraphic *g_gfxTable[];
extern KGraphic *g_gfxSparkA;
extern KGraphic *g_gfxExplodeDebris;
extern KGraphic *g_debrisParticleGfx;
extern KGraphic *g_gfxSpark;
extern KGraphic *g_gfxMissileSpark;
extern KGraphic *g_gfxBossBurst;
extern KGraphic *g_gfxObjExplode;
extern char g_strN[260];
extern int g_hazard0GfxW;
extern char g_sScore[];
extern char g_gfxPath[];
extern LARGE_INTEGER g_timeStampB;
extern HiscoreData g_hiscoreMagic;
extern LevelRec g_replayRecs[5][4000];
extern char g_strS[260];
extern float g_fadeVolume1;
extern FadeColors g_colG[];
extern float g_starZ[3000];
extern int g_meterValue;
extern char g_serial[16];
extern int g_typeKillCombo[];
extern int g_pend3Vol;
extern BonusStats g_bonusTally[];
extern __int64 g_p2Bonus;
extern PulseFx g_fx[];
extern Spark g_sparks[2000];
extern int g_bonusItemField34;
extern float g_savedEnemyY;
extern int g_lastActivityTime;
extern int g_diamondBigGfxW;
extern char g_warpMalfunctionMsg[];
extern float g_enemyVelYScratch;
extern VoidFn g_grabEnemyFn;
extern int g_joyCount;
extern int g_sampleHandle[10];
extern float g_levelDist;
extern char g_newPass[];
extern float g_fxBlueColorLevel;
extern LevelRaw g_levelRaw;
extern int g_portalGfxH;
extern int g_tallyTime;
extern KGraphic *g_starGfx[];
extern Rect16 g_rectsB[6];
extern Account g_accBuf[];
extern int g_hazard5GfxH;
extern float g_cosDeg[360];
extern int g_mothershipMaskW;
extern int g_logoBirdFlareGfxH;
extern unsigned int g_cursorBlinkTime;
extern int g_pend4Freq;
extern int g_win7;
extern int g_uiBlink;
extern int g_triggerX[];
extern unsigned int g_uiBlinkTime;
extern float g_savedEnemyX;
extern unsigned char g_blocks[6][1024];
extern WSADATA g_wsaData;
extern int g_moneySuckerHeight;
extern int g_hazard2GfxW;
extern int g_frameCount;
extern char g_sMode[];
extern char g_news3[];
extern int g_accSizes[];
extern Flash34 g_logoFlashes[49];
extern char g_name[];
extern short g_animRowScratch;
extern unsigned int g_rngW;
extern int g_hazard1GfxW;
extern KGraphic *g_gfxSword;
extern float g_pend0Pan;
extern char g_levelBannerText[];
extern int g_meteorsGfxW;
extern int g_groupEnemyCount[];
extern float g_fadeVolume0;
extern char g_bannerMsg[];
extern AccountV0 g_accV0;
extern MenuEntry g_menuEntries[85];
extern float g_sfxPanIdx;
extern MapObj g_mapObjs[100];
extern unsigned long g_bltFastFlags;
extern char g_pathBuf[];
extern int g_patternCount;
extern int g_hiscorePackedSize;
extern int g_curWin;
extern ScoopTrail g_scoop[];   // 15 in all; globals.cpp defines [1] + g_scoopRest_d622f0[14]
extern int g_frameAY2;
extern unsigned int g_raceStartTime;
extern unsigned int g_rngX;
extern Window g_windows[10];
extern char g_strT[260];
extern unsigned int g_frameTime;
extern float g_starA[3000];
extern char g_logBuf[];
extern int g_hazard1GfxH;
extern VoidFn g_shipHudFn;
extern char g_strI[260];
extern int g_portalGfxH2;
extern short g_enemyDamageStage[2][150];
extern char g_strB[260];
extern int g_meteorBonusesGfxH;
extern FadeColors g_colB[];
extern ScorePopup g_popups[];
extern float g_fadeVolume3;
extern float g_cosTable[3600];
extern int g_pend2Vol;
extern float g_fadePan0;
extern char g_news2[];
extern char g_moneyBuf0[];
extern int g_frameAY1;
extern float g_raceDistanceLeft;
extern FARPROC g_nviewLibLoad;
extern char g_sDate[];
extern int g_logoBirdFlareGfxW;
extern float g_pend5Pan;
extern int g_bonusVolume[46];
extern OSVERSIONINFOA g_osvi;
extern unsigned char g_autoplay;
extern unsigned char g_fileWriteErrorFlag;
extern bool g_linkHover;
extern unsigned char g_mirrorLevel;
extern int g_voiceSearchTries;
extern void *g_levelBufA;
extern void *g_levelBufB;
extern int g_cheatKillSwitch;
extern int g_mouseDown;
extern int g_mouseClick;
extern int g_rightButton;
extern int g_cursor;
extern int g_editing;
extern unsigned char g_autoplayCanFire;
extern unsigned char g_mouseFlag;
extern unsigned char g_presets;
extern unsigned char g_restartNeeded;
extern int g_pauseCount;
extern int g_idleFrames;
extern unsigned int g_splashEnd;
extern unsigned int g_splashMinEnd;
extern int g_rankFanfarePlayed;
extern int g_buttonsOn;
extern int g_volumeSnapClick;
extern int g_mouseClickHandled;
extern unsigned char g_joy0;
extern unsigned char g_joy1;
extern unsigned char g_windowed;
extern bool g_windowedAtStartup;
extern int g_saveMagic;
extern void *g_ship1Hma;
extern void *g_ship2Hma;
extern void *g_hmaWeaponsBig;
extern void *g_alienGfxMem[6];
extern void *g_shutdownPtrA;
extern void *g_shutdownPtrB;
extern void *g_hmaDiamond;
extern void *g_hmaDiamondBig;
extern void *g_hmaBonuses;
extern void *g_hmaRocket;
extern void *g_hmaMarks;
extern int g_hmaMothership;
extern void *g_hmaMoneySucker;
extern void *g_hmaMoneyShip;
extern void *g_hmaGuard;
extern void *g_hmaLogoBirdFlare;
extern void *g_hmaMeteors;
extern void *g_hmaMeteorBonuses;
extern KWindow *g_window;
extern KGraphic *g_gfxFighter1;
extern KGraphic *g_gfxFighter2;
extern KGraphic *g_tinyFont;
extern KGraphic *g_smallFont;
extern KGraphic *g_digitFont;
extern KGraphic *g_fontGfx;
extern KGraphic *g_gfxSparks;
extern KGraphic *g_gfxLogos;
extern KGraphic *g_gfxLogo3;
extern KGraphic *g_gfxLogo3Glow;
extern KGraphic *g_gfxGameOver;
extern KGraphic *g_gfxSkull;
extern KGraphic *g_gfxWeaponsBig;
extern KGraphic *g_gfxFighterFire2;
extern IntPair g_alienGfxCache[6];
extern KGraphic *g_gfxDiamond;
extern KGraphic *g_gfxDiamondBig;
extern KGraphic *g_gfxPause;
extern KGraphic *g_gfxBonus;
extern KGraphic *g_gfxRocket;
extern KGraphic *g_gfxCoins;
extern KGraphic *g_gfxMedals;
extern KGraphic *g_gfxRanks;
extern KGraphic *g_gfxRankIcons;
extern KGraphic *g_gfxMemoryBlocks;
extern KGraphic *g_gfxMothership;
extern KGraphic *g_gfxMothershipMask;
extern KGraphic *g_gfxMoneySucker;
extern KGraphic *g_gfxMoneySuckerMask;
extern KGraphic *g_gfxMoneyShip;
extern KGraphic *g_gfxMoneyShipMask;
extern KGraphic *g_gfxBorderEasy;
extern KGraphic *g_gfxBorderNormal;
extern KGraphic *g_gfxBorderHard;
extern KGraphic *g_gfxBorderAce;
extern KGraphic *g_gfxGuard;
extern KGraphic *g_gfxGuardMask;
extern KGraphic *g_gfxBeam;
extern KGraphic *g_explGfx;
extern KGraphic *g_explGfx2;
extern KGraphic *g_numbersGfx;
extern KGraphic *g_gfxShopBg;
extern KGraphic *g_gfxSecretScreen;
extern KGraphic *g_gfxSecretPic;
extern KGraphic *g_creditPic;
extern KGraphic *g_splash;
extern KGraphic *g_endImg;
extern KGraphic *g_gfxShopItemPic;
extern KGraphic *g_bgGraphic;
extern KGraphic *g_gfxMeteorMeter;
extern KGraphic *g_gfxMeteorBonuses;
extern KGraphic *g_gfxFlare1;
extern KGraphic *g_gfxFlare2;
extern KGraphic *g_gfxFlare3;
extern KGraphic *g_gfxFlare4;
extern KGraphic *g_gfxFlare5;
extern KGraphic *g_gfxFlare6;
extern KGraphic *g_gfxFlare7;
extern KGraphic *g_gfxFlare8;
extern KGraphic *g_gfxFlare9;
extern KGraphic *g_gfxFlare10;
extern KGraphic *g_gfxFlare11;
extern KGraphic *g_gfxFlare12;
extern KGraphic *g_gfxFlare13;
extern KGraphic *g_gfxFlare14;
extern KGraphic *g_gfxFlare15;
extern KGraphic *g_gfxFlare16;
extern KGraphic *g_gfxFlare17;
extern KGraphic *g_gfxFlare18;
extern KGraphic *g_gfxFlare19;
extern KGraphic *g_gfxFlare20;
extern KGraphic *g_gfxFlare21;
extern KGraphic *g_gfxFlare23;
extern KGraphic *g_gfxFlare24;
extern KGraphic *g_gfxFlare25;
extern KGraphic *g_gfxFlare26;
extern KGraphic *g_gfxFlare27;
extern KGraphic *g_gfxFlare28;
extern KGraphic *g_gfxFlare29;
extern KGraphic *g_gfxFlare30;
extern KGraphic *g_gfxFlare31;
extern KGraphic *g_gfxFlare32;
extern KGraphic *g_gfxFlare33;
extern KGraphic *g_gfxFlare34;
extern KGraphic *g_gfxStar1;
extern KGraphic *g_starSprite;
extern KGraphic *g_gfxStar3;
extern KGraphic *g_gfxLogoFighter;
extern KGraphic *g_gfxLogoFighterShadow;
extern KGraphic *g_gfxLogoBird;
extern KGraphic *g_gfxLogoSword;
extern KGraphic *g_gfxLogoSwordGlow;
extern KGraphic *g_gfxShieldNew;
extern KGraphic *g_gfxFlareSpark;
extern KGraphic *g_gfxFlareBomb;
extern KGraphic *g_gfxFlareBomb2;
extern KGraphic *g_gfxFlareBomb3;
extern KGraphic *g_gfxFlareAtmos;
extern KGraphic *g_flashGfx;
extern KGraphic *g_gfxFlareStreakBig;
extern KGraphic *g_gfxFlareLaser;
extern KGraphic *g_gfxFlareStreakGuard;
extern KGraphic *g_sparkGfx;
extern KGraphic *g_gfxFlareScoop;
extern KGraphic *g_gfxLogoBirdFlare;
extern KGraphic *g_beamSparkGfxP0;
extern KGraphic *g_beamSparkGfxP1;
extern KGraphic *g_gfxFlarePlanet;
extern KGraphic *g_bg1;
extern KGraphic *g_bg2;
extern KGraphic *g_bg3;
extern KGraphic *g_bg4;
extern KGraphic *g_bg5;
extern KGraphic *g_winGfx;
extern float g_bgScroll;
extern float g_angle0;
extern unsigned char g_keysChanged;
extern bool g_showFps;
extern unsigned char g_enemyActedThisFrame;
extern int g_blitErrors;
extern int g_profileCollisions;
extern float g_frameDt;
extern int g_skipLogoFlag;
extern unsigned int g_soundStealCooldown;
extern unsigned int g_nextSpark;
extern unsigned int g_flameTimerP0;
extern unsigned int g_flameTimerP1;
extern unsigned int g_scoopTimerP0;
extern unsigned int g_scoopTimerP1;
extern unsigned int g_flameTimerP0Alt;
extern unsigned int g_flameTimerP1Alt;
extern unsigned int g_scoopTimerP0Alt;
extern unsigned int g_scoopTimerP1Alt;
extern int g_rocketRepeatTimer;
extern unsigned int g_statSubmitCooldown;
extern int g_debug;
extern int g_inputCooldown;
extern float g_fxSpinAngle;
extern float g_fxAngleStep;
extern int g_shopClosing;
extern int g_levelIdleCounter;
extern int g_altFireToggle;
extern int g_hiscoreEntryReset;
extern int g_tallyDonePending;
extern int g_titleResetPending;
extern int g_advanceScreenFlag;
extern int g_textCursorY;
extern int g_curY;
extern int g_cursorX;
extern int g_textStartX;
extern int g_resetFlag;
extern float g_hiscoreEntryScale;
extern unsigned char g_levelStartLatch;
extern unsigned char g_boostReleased;
extern unsigned char g_isBossLevel;
extern unsigned char g_isWaveLevel;
extern float g_boostCharge;
extern float g_baseSpeedRamp;
extern int g_fastFrameCount;
extern int g_slowFrameCount;
extern float g_speedPct;
extern int g_bgTint;
extern int g_fadeStep;
extern int g_fadeColorSet;
extern int g_explSrcY[];
extern unsigned char g_flag;
extern unsigned char g_drunk;
extern unsigned char g_screenTestDone;
extern unsigned char g_openGL;
extern int g_beamLevel;
extern int g_ringCount;
extern float g_starPulseAlpha;
extern int g_clipTop;
extern int g_clipBottom;
extern int g_clipLeft;
extern int g_clipRight;
extern float g_starZNear;
extern int g_bossBurstTimer;
extern float g_diffHpBonusA;
extern float g_diffHpBonusB;
extern int g_bossGunCountA;
extern int g_bossGunCountB;
extern int g_bossGunCountC;
extern int g_type3EnemySpawnCount;
extern int g_alienAttackTimer;
extern int g_alienAttackTimerStep;
extern int g_guardTriggerFlag;
extern float g_transitionRate;
extern int g_numLevels2;
extern char g_musicPlaying;
extern unsigned char g_loginWinOpen;
extern unsigned int g_meterShowUntil;
extern float g_angVelX;
extern float g_angX;
extern float g_angVelY;
extern float g_angY;
extern float g_angVelZ;
extern float g_angZ;
extern float g_targetX;
extern float g_targetY;
extern unsigned int g_menuIdleTimeout;
extern unsigned int g_timeTrialDeadline;
extern int g_timeTrialLocked;
extern int g_lastEventTime;
extern unsigned int g_timerB;
extern unsigned int g_timerA;
extern int g_getReadyFlagA;
extern int g_memoryDone;
extern int g_memoryBonusPending;
extern int g_memoryIntro;
extern int g_raceActive;
extern int g_gemDropIntroActive;
extern int g_hiscoreSkipGateActive;
extern int g_rankMsgActive;
extern unsigned int g_rankLockUntil;
extern unsigned int g_rankPopupMinTime;
extern int g_resultsScreenEndTime;
extern unsigned int g_memoryIntroTimer;
extern unsigned int g_memoryStationDeadline;
extern int g_gemDropIntroTimer;
extern int g_deathSeqActive;
extern int g_transitionLockUntil;
extern int g_transitionLock;
extern int g_malfunctionAlarmTime;
extern unsigned int g_playerStallTime;
extern int g_inRandom;
extern float g_borderScroll;
extern unsigned int g_levelBannerTime;
extern unsigned int g_msgTimer;
extern unsigned int g_alertTextTime;
extern unsigned int g_msgTime;
extern unsigned int g_bannerMsgTime;
extern int g_warpMsgBlinkTime;
extern unsigned int g_bonusResultsTime;
extern unsigned int g_perfectCheckDelay;
extern int g_secretShown;
extern int g_animFrame;
extern int g_newsIds[4];
extern int g_newsA[4];
extern int g_newsB[4];
extern int g_tickerIdx;
extern int g_activePlayerBlink;
extern unsigned int g_activePlayerBlinkTime;
extern int g_colorPhase1;
extern int g_colorPhase2;
extern int g_colorPhase3;
extern int g_introDone;
extern int g_levelStartFlag;
extern int g_shopSelItem;
extern HMODULE g_nviewLib;
extern int g_musicRestartTime;
extern int g_songCount;
extern int g_songIndex;
extern BASS_DWORD g_songLengthMs;
extern int g_songEndTime;
extern int g_soundEnabled;
extern int g_soundQueueCount;
extern unsigned int g_soundQueueNext;
extern int g_sndFlags;
extern int g_sndFlags2;
extern BASS_DWORD g_chanScopeHum;
extern BASS_DWORD g_chanShieldHum;
extern BASS_DWORD g_musicPos;
extern BASS_DWORD g_musicHandle;
extern BASS_DWORD g_musicStream;
extern int g_fadeQueueSample1;
extern int g_fadeQueueSample2;
extern int g_fadeQueueSample3;
extern int g_fadeQueueSample4;
extern BASS_DWORD g_sfxAlienShoot1;
extern BASS_DWORD g_sfxAlienShoot2;
extern BASS_DWORD g_sfxAlienShoot3;
extern BASS_DWORD g_sfxAlienShoot4;
extern BASS_DWORD g_sndAlienShoot5;
extern BASS_DWORD g_sfxAlienShoot6;
extern BASS_DWORD g_sfxAlienShoot7;
extern BASS_DWORD g_sfxAlienShoot8;
extern BASS_DWORD g_sfxAlienShoot9;
extern BASS_DWORD g_sndAlienShoot10;
extern BASS_DWORD g_sfxAlienShoot11;
extern BASS_DWORD g_sndAlienShoot12;
extern BASS_DWORD g_sfxAlienShoot12Alt;
extern BASS_DWORD g_sfxAlienShoot13;
extern BASS_DWORD g_sfxAlienShoot14;
extern BASS_DWORD g_sfxAlienShoot15;
extern BASS_DWORD g_sfxAlienShoot16;
extern BASS_DWORD g_sfxAlienShoot17;
extern BASS_DWORD g_sfxAlienShoot18;
extern BASS_DWORD g_sfxTast;
extern BASS_DWORD g_sfxBell1;
extern BASS_DWORD g_sfxBell2;
extern BASS_DWORD g_sfxBell3;
extern BASS_DWORD g_sfxBigFire;
extern BASS_DWORD g_sfxBigSmall;
extern BASS_DWORD g_sfxHit1;
extern BASS_DWORD g_sfxHit2;
extern BASS_DWORD g_sfxHit3;
extern BASS_DWORD g_sfxHit4;
extern BASS_DWORD g_sfxClickGeneric;
extern BASS_DWORD g_sfxOver;
extern BASS_DWORD g_sfxFoundIt;
extern BASS_DWORD g_sfxBing;
extern BASS_DWORD g_sfxBirth;
extern BASS_DWORD g_sfxChaching;
extern BASS_DWORD g_sfxCash;
extern BASS_DWORD g_sfxExplo1;
extern BASS_DWORD g_sfxExplo2;
extern BASS_DWORD g_sfxExplo3;
extern BASS_DWORD g_sfxExplo4;
extern BASS_DWORD g_sfxExplo5;
extern BASS_DWORD g_sfxGuit;
extern BASS_DWORD g_sfxFanfare;
extern BASS_DWORD g_sfxFanfare1;
extern BASS_DWORD g_sfxLaser1;
extern BASS_DWORD g_sfxLaser2;
extern BASS_DWORD g_sfxOrkHit;
extern BASS_DWORD g_sfxShot1;
extern BASS_DWORD g_sfxShot2;
extern BASS_DWORD g_sfxWaom;
extern BASS_DWORD g_sfxWooing;
extern BASS_DWORD g_sfxWaauw;
extern BASS_DWORD g_sfxZuzk;
extern BASS_DWORD g_sfxJangle;
extern BASS_DWORD g_sfxHarpGliss1;
extern BASS_DWORD g_sfxMachine;
extern BASS_DWORD g_sfxRocket;
extern BASS_DWORD g_sfxMouww;
extern BASS_DWORD g_sfxPing;
extern BASS_DWORD g_sfxWarp;
extern BASS_DWORD g_sfxWarp2;
extern BASS_DWORD g_sfxWarp3;
extern BASS_DWORD g_sfxWheommm;
extern BASS_DWORD g_sfxScopeHum;
extern BASS_DWORD g_sfxShieldHum;
extern BASS_DWORD g_sfxMotherLoop;
extern BASS_DWORD g_sfxGuardLoop;
extern BASS_DWORD g_sfxBossLoop;
extern BASS_DWORD g_sfxShipHumLoop;
extern BASS_DWORD g_sfxAlienAttack;
extern BASS_DWORD g_sfxAlienAttack2;
extern BASS_DWORD g_sfxAlienAttack3;
extern BASS_DWORD g_sfxAlienAttack4;
extern BASS_DWORD g_sfxAlienAttack5;
extern BASS_DWORD g_sfxMeteorPass;
extern BASS_DWORD g_sfxDeath;
extern BASS_DWORD g_sfxCapture;
extern BASS_DWORD g_sfxSlide;
extern BASS_DWORD g_sfxKanganang;
extern BASS_DWORD g_sfxJingles;
extern BASS_DWORD g_sfxHahaha;
extern BASS_DWORD g_sfxMothership;
extern BASS_DWORD g_sfxPing2;
extern BASS_DWORD g_sfxCoin;
extern BASS_DWORD g_sfxCurrent;
extern BASS_DWORD g_sfxRollover;
extern BASS_DWORD g_sfxBuzzer;
extern BASS_DWORD g_sfxBuzzer2;
extern BASS_DWORD g_sfxMoneyBomb;
extern BASS_DWORD g_sfxGemBomb;
extern BASS_DWORD g_sfxWindow;
extern BASS_DWORD g_sfxMinimize;
extern BASS_DWORD g_sfxButtonClick;
extern BASS_DWORD g_sfxZoom;
extern BASS_DWORD g_sfxMetal;
extern BASS_DWORD g_sfxSword;
extern BASS_DWORD g_sfxThump;
extern BASS_DWORD g_sfxThumpBig;
extern BASS_DWORD g_sfxSwoosh;
extern BASS_DWORD g_sfxComing;
extern BASS_DWORD g_sfxWhip;
extern BASS_DWORD g_sfxFalling;
extern BASS_DWORD g_sfxSingleShot;
extern BASS_DWORD g_sfxBonus;
extern BASS_DWORD g_sfxExtraBullet;
extern BASS_DWORD g_sfxExtraLife;
extern BASS_DWORD g_sfxExtraSpeed;
extern BASS_DWORD g_sfxExtraTime;
extern BASS_DWORD g_sfxGetReady;
extern BASS_DWORD g_sfxGetReady2;
extern BASS_DWORD g_sfxGetReady3;
extern BASS_DWORD g_sfxHurryUp1;
extern BASS_DWORD g_sfxHurryUp2;
extern BASS_DWORD g_sfxMoney;
extern BASS_DWORD g_sfxScoop;
extern BASS_DWORD g_sfxShield;
extern BASS_DWORD g_sfxSingleShotVoice;
extern BASS_DWORD g_sfxDoubleShot;
extern BASS_DWORD g_sfxSucker;
extern BASS_DWORD g_sfxSucker2;
extern BASS_DWORD g_sfxSucker3;
extern BASS_DWORD g_sfxSuperTripleShot;
extern BASS_DWORD g_sfxTripleShot;
extern BASS_DWORD g_sfxQuadShot;
extern BASS_DWORD g_sfxRankEnsign;
extern BASS_DWORD g_sfxRankLieutenant;
extern BASS_DWORD g_sfxRankCommander;
extern BASS_DWORD g_sfxRankCaptain;
extern BASS_DWORD g_sfxRankAdmiral;
extern BASS_DWORD g_sfxAlright;
extern BASS_DWORD g_sfxCongratulations;
extern BASS_DWORD g_sfxArmour;
extern BASS_DWORD g_sfxBonusUnused;
extern BASS_DWORD g_sfxMeteorStorm;
extern BASS_DWORD g_sfxMemoryStation;
extern BASS_DWORD g_sfxOops;
extern BASS_DWORD g_sfxPlayer1;
extern BASS_DWORD g_sfxPlayer2;
extern BASS_DWORD g_sfxWarning;
extern BASS_DWORD g_sfxWarpMalfunction;
extern BASS_DWORD g_sfxWelcome;
extern BASS_DWORD g_sfxVoiceLetterE;
extern BASS_DWORD g_sfxVoiceLetterX;
extern BASS_DWORD g_sfxVoiceLetterT;
extern BASS_DWORD g_sfxVoiceLetterR;
extern BASS_DWORD g_sfxVoiceLetterA;
extern BASS_DWORD g_sampleSecret;
extern BASS_DWORD g_sfxGameOver;
extern BASS_DWORD g_sfxTimes2;
extern BASS_DWORD g_sfxTimes5;
extern BASS_DWORD g_sfxPerfect;
extern BASS_DWORD g_sfxGoodbye;
extern BASS_DWORD g_sfxFreeze;
extern BASS_DWORD g_sfxGemDrop;
extern BASS_DWORD g_sfxPlayer;
extern BASS_DWORD g_sfxPlayers;
extern BASS_DWORD g_sfxAutofire;
extern BASS_DWORD g_sfxDrunk;
extern BASS_DWORD g_sfxMirror;
extern BASS_DWORD g_sfxShop1;
extern BASS_DWORD g_sfxShop2;
extern BASS_DWORD g_sfxShop3;
extern BASS_DWORD g_sfxShop4;
extern BASS_DWORD g_sfxShop5;
extern BASS_DWORD g_sfxVoiceOne;
extern BASS_DWORD g_sfxVoiceTwo;
extern BASS_DWORD g_sfxVoiceThree;
extern BASS_DWORD g_sfxVoiceFour;
extern BASS_DWORD g_sfxVoiceFive;
extern BASS_DWORD g_sfxVoiceSix;
extern BASS_DWORD g_sfxVoiceSeven;
extern BASS_DWORD g_sfxVoiceEight;
extern BASS_DWORD g_sfxVoiceNine;
extern BASS_DWORD g_sfxVoiceTen;
extern BASS_DWORD g_sfxRankKnight;
extern BASS_DWORD g_sfxRankLord;
extern BASS_DWORD g_sfxRankOverlord;
extern BASS_DWORD g_sfxRankGrandmaster;
extern BASS_DWORD g_sfxRankChampion;
extern BASS_DWORD g_sfxRankGod;
extern BASS_DWORD g_sfxStar;
extern BASS_DWORD g_sfxStars;
extern BASS_DWORD g_sfxWarblade;
extern BASS_DWORD g_sfxRankBronze;
extern BASS_DWORD g_sfxRankSilver;
extern BASS_DWORD g_sfxRankGold;
extern BASS_DWORD g_sfxOhNo;
extern BASS_DWORD g_sfxBomb;
extern BASS_DWORD g_sfxRankMarker;
extern BASS_DWORD g_sfxGotcha;
extern BASS_DWORD g_sfxSpeed;
extern BASS_DWORD g_sfxPlanetPluto;
extern BASS_DWORD g_sfxPlanetNeptune;
extern BASS_DWORD g_sfxPlanetUranus;
extern BASS_DWORD g_sfxPlanetSaturn;
extern BASS_DWORD g_sfxPlanetJupiter;
extern BASS_DWORD g_sfxPlanetMars;
extern BASS_DWORD g_sfxPlanetTellus;
extern BASS_DWORD g_sfxPlanetVenus;
extern BASS_DWORD g_sfxPlanetMercury;
extern BASS_DWORD g_sfxPlanetSol;
extern BASS_DWORD g_sfxUltimateRank;
extern BASS_DWORD g_sfxRank;
extern BASS_DWORD g_sfxAvailable;
extern BASS_DWORD g_sfxPlanet;
extern BASS_DWORD g_sfxNew;
extern BASS_DWORD g_sfxYouAreThe;
extern unsigned char g_warpWhooshPlayed;
extern unsigned char g_bonusMeterStarted;
extern unsigned char g_gadgetHitLatch;
extern unsigned char g_mouseOverTextItem;
extern int g_coinSrcX[];
extern int g_itemBonusSrcX[];
extern int g_warpCheckCount;
extern int g_warpMalfunctionCount;
extern float g_scoopRange;
extern float g_scoopTrailScale;
extern float g_meterV;
extern int g_nextId;
extern int g_lastLeft;
extern int g_lastRight;
extern int g_lastTop;
extern int g_lastBottom;
extern int g_last2Left;
extern int g_last2Right;
extern int g_last2Top;
extern int g_last2Bottom;
extern int g_nextX;
extern unsigned char g_buttonHitLatch;
extern unsigned char g_winDragActive;
extern bool g_newGameOnClose;
extern int g_dragDX;
extern int g_dragDY;
extern int g_linkCount;
extern int g_enemyFrameCounter;
extern int g_savedDifficultyTT;
extern int g_cfgBackup;
extern int g_hudY;
extern __int64 g_bestScore;
extern int g_hiscoreInsertGate;
extern int g_hsTable[4];
extern int g_nameLen;
extern char g_hiscoreTransitionFlag;
extern unsigned char g_superGemDrop;
extern unsigned char g_noProfilesError;
extern unsigned char g_profileReadOnly;
extern int g_bonusItemCount;
extern int g_pickupCount;
extern int g_bossGunActiveA;
extern int g_bossGunActiveB;
extern int g_bossGunActiveC;
extern int g_alienGfxBufferedCount;
extern int g_gfxLoaded;
extern int g_gfx2Loaded;
extern int g_hmaLoaded;
extern int g_alienGfxFreedA;
extern int g_alienGfxFreedB;
extern int g_alienGfxFreedM;
extern int g_freedA;
extern int g_freedB;
extern int g_freedC;
extern int g_numMalfunction;
extern int g_gridX;
extern int g_gridY;
extern int g_memSelValid;
extern int g_memSelRow;
extern int g_memSelCol;
extern int g_memCursorFrame;
extern unsigned int g_gridAnimTime;
extern unsigned int g_memStageDeadline;
extern unsigned int g_memPickResolveTime;
extern int g_pairsTickTime;
extern int g_pauseShiftedTimerE;
extern int g_toggleOnCount;
extern int g_toggleOffCount;
extern int g_profileCount;
extern unsigned char g_profileWinOpen;
extern unsigned char g_quitGameWinOpen;
extern bool g_quitToWindowsWinOpen;
extern bool g_dialogWinOpen;
extern unsigned char g_itemSteered;
extern unsigned char g_newVersion;
extern unsigned char g_loggedIn;
extern bool g_endWobbleActive;
extern __int64 g_shownStat;
extern int g_newGamePending;
extern int g_bonusFlag;
extern int g_moneyBlinkTimer;
extern int g_hudSpeedBarTick;
extern __int64 g_scoreBefore;
extern bool g_endWobbleEnabled;
extern unsigned char g_customSongs;
extern unsigned char g_soundPaused;
extern bool g_extraLifeGranted;
extern sockaddr_in g_sockAddr;
extern int g_slotCount;
extern int g_curSong;
extern char *g_playlistBuf;
extern int g_playlistSize;
extern int g_playlistCount;
extern BASS_DWORD g_curStream;
extern BASS_DWORD g_pend0;
extern BASS_DWORD g_pend1;
extern BASS_DWORD g_pend2;
extern BASS_DWORD g_pend3;
extern BASS_DWORD g_pend4;
extern BASS_DWORD g_pend5;
extern float g_scanY;
extern int g_newGameResetVal;
extern int g_cheatDetectFlag;
extern int g_errPos;
extern int g_errDiv;
extern bool g_newsReady;
extern bool g_playTimeAdded;
extern bool g_profilePlayTimeAdded;
extern int g_shownRank;
extern int g_introGateScratch;
extern int g_memoryStationExitFlag;
extern float g_dt;
extern int g_skipRender;
extern bool g_saveMsgToggle;
extern bool g_hasLives;
extern unsigned char g_promoRingActive;
extern unsigned char g_promoSpecialRank;
extern int g_lives;
extern int g_lastLevelBuffered;
extern float g_shopShake;
extern int g_engineDroneFreq;
extern int g_engineDroneFreqStep;
extern int g_completePopupYOffset;
extern unsigned int g_moneySuckerCooldown;
extern int g_aiRight;
extern int g_aiLeft;
extern unsigned int g_sndTHit3;
extern unsigned int g_sndTHit4;
extern unsigned int g_sndTHit1;
extern unsigned int g_sndTHit2;
extern unsigned int g_sndTCurrent;
extern unsigned int g_sndTExplo1;
extern unsigned int g_sndTExplo2;
extern unsigned int g_sndTExplo4;
extern unsigned int g_sndTExplo5;
extern unsigned int g_sndTMouww;
extern int g_newsUntil;
extern int g_memUntil;
extern int g_hiscoreStarCount;
extern int g_hiscoreStarBrightness1;
extern int g_hiscoreStarBrightness2;
extern int g_hiscoreStarBrightness3;
extern int g_tipIndex;
extern int g_promoRingIndex;
extern int g_streakColorB;
extern float g_streakX;
extern float g_streakAlpha;
extern unsigned char g_streakActive;
extern unsigned char g_introStageCenter;
extern unsigned char g_introStageLeftWing;
extern unsigned char g_introStageRightWing;
extern float g_bannerShrinkSpeed;
extern float g_leftWingX;
extern float g_rightWingX;
extern float g_wordmarkOffsetX;
extern float g_convergeFlash;
extern unsigned char g_introStageWordmark;
extern unsigned char g_introStageBanner;
extern unsigned char g_introStageFlash;
extern unsigned char g_introStageFinal;
extern float g_starScale;
extern float g_starAlpha;
extern float g_starAlphaStep;
extern unsigned char g_introSoundPlayed[9];
extern unsigned char g_introBlockedByWindow;
extern unsigned char g_autoConfirmName;
extern bool g_promoContinueBlink;
extern __int64 g_bestSent[6];
extern float g_wobble;
extern int g_moneyW0;
extern int g_moneyW1;
extern int g_moneyW2;
extern int g_moneyW3;
extern unsigned int g_promoBlinkTimer;
extern int g_debrisSpawnedCount;
extern int g_secretBirdHitCount;
extern int g_flare0;
extern int g_flare1;
extern int g_flare2;
extern int g_flare3;
extern int g_shipX;
extern int g_shipY;
extern float g_shieldAngle;
extern int g_flameXP0;
extern int g_flameXP1;
extern int g_scoopXP0;
extern int g_scoopXP1;
extern int g_flameXP0Alt;
extern int g_flameXP1Alt;
extern int g_scoopXP0Alt;
extern int g_scoopXP1Alt;
extern int g_perfectAny;
extern int g_perfectAwardedP0;
extern int g_perfectAwardedP1;
extern float g_endG;
extern float g_endR;
extern float g_endB;
extern int g_floorY;
extern unsigned int g_saveMsgBlinkRate;
extern int g_prices[];
extern __int64 g_enemyScoreTable[50];
extern __int64 g_comboBonusTable[];
extern __int64 g_rankBonusTable[];
extern int g_ovX1;
extern int g_ovY1;
extern int g_ovX2;
extern int g_ovY2;
extern LARGE_INTEGER g_timeMarkC;
extern BlitItem g_blit2[];
extern FILETIME g_timerEnd1;
extern float g_sinTableFine[];
extern SYSTEMTIME g_sysTime;
extern __int64 g_timerMin2;
extern BlitItem g_blit[];
extern FILETIME g_timerStart2;
extern char g_numBuf[];
extern int g_ovW;
extern int g_offYB;
extern int g_idxA;
extern StretchItemRot g_stretchRot[];
extern StretchItemI g_stretchI[];
extern int g_offXB;
extern int g_ovH;
extern BYTE g_keyState[];
extern char g_keyName[];
extern int g_idxB;
extern unsigned int g_layoutGuard;
extern HWND g_hwnd;
extern FILETIME g_timeD;
extern FILETIME g_timeE;
extern int g_pendingLevelsPlayed;
extern DWORD g_vidMemFree;
extern HKL g_layout;
extern QuadItem g_quad[];
extern __int64 g_timerMin1;
extern int g_offXA;
extern DWORD g_vidMemTotal;
extern FILETIME g_timerStart1;
extern FILETIME g_timeMarkB;
extern int g_offYA;
extern int g_moneyMax;
extern StretchItemRot g_stretchRot2[];
extern StretchItemF g_stretchF[];
extern LARGE_INTEGER g_timeA;
extern FILETIME g_timerEnd2;
extern WORD g_asciiBuf[];
extern float g_cosTableFine[];
extern int g_screenHInit;
extern int g_offsetXi;
extern int g_offsetYi;
extern float g_offsetX;
extern float g_offsetY;
extern float g_worldViewRotation;
extern float g_worldViewX;
extern float g_worldViewY;
extern int g_stretchICount;
extern int g_stretchFCount;
extern int g_stretchRotCount;
extern int g_stretchRot2Count;
extern int g_blitCount;
extern int g_blit2Count;
extern int g_blit3Count;
extern int g_quadCount;
extern int g_quadCountMax;
// 0xf979ec is not a game global: it is the CRT's `_fmode` (libcmtd's .bss, next to
// __adjust_fdiv); the game sets it to _O_BINARY (0x8000) before opening files.
// Alias the name onto the CRT's variable so a rebuild's writes still reach it.
extern "C" int _fmode;
#define g_fileModeFlag _fmode

// Accesses that land inside an element of an array are spelled against the real
// array, not as separate globals at shifted addresses.
